SubModules:
  LayoutDetection:
    layout_merge_bboxes_mode: small
    layout_nms: true
    layout_unclip_ratio: 1.0
    # model_dir: /Users/doudou/.paddlex/official_models/PP-DocLayout-L
    # model_name: RT-DETR-H_layout_3cls
    # model_name: RT-DETR-H_layout_17cls
    # model_name: PP-DocLayout_plus-L
    model_name: PP-DocLayout-L
    module_name: layout_detection
    threshold: 0.3
    # threshold: 
    #   0: 0.3  # paragraph_title
    #   1: 0.5  # image
    #   2: 0.5  # text
    #   3: 0.5  # number
    #   4: 0.5  # abstract
    #   5: 0.5  # content
    #   6: 0.5  # figure_title
    #   7: 0.3  # formula
    #   8: 0.5  # table
    #   9: 0.5  # table_title
    #   10: 0.5 # reference
    #   11: 0.5 # doc_title
    #   12: 0.5 # footnote
    #   13: 0.5 # header
    #   14: 0.5 # algorithm
    #   15: 0.5 # footer
    #   16: 0.1 # seal
    #   17: 0.5 # chart_title
    #   18: 0.5 # chart
    #   19: 0.5 # formula_number
    #   20: 0.5 # header_image
    #   21: 0.5 # footer_image
    #   22: 0.5 # aside_text
    # layout_unclip_ratio:
    #   0: [1.0, 1.0]  # paragraph_title
    #   1: [1.0, 1.0]  # image
    #   2: [1.0, 1.0]  # text
    #   3: [1.0, 1.0]  # number
    #   4: [1.0, 1.0]  # abstract
    #   5: [1.0, 1.0]  # content
    #   6: [1.0, 1.0]  # figure_title
    #   7: [1.0, 1.0]  # formula
    #   8: [1.0, 1.0]  # table
    #   9: [1.0, 1.0]  # table_title
    #   10: [1.0, 1.0] # reference
    #   11: [1.0, 1.0] # doc_title
    #   12: [1.0, 1.0] # footnote
    #   13: [1.0, 1.0] # header
    #   14: [1.0, 1.0] # algorithm
    #   15: [1.0, 1.0] # footer
    #   16: [1.0, 1.0] # seal
    #   17: [1.0, 1.0] # chart_title
    #   18: [1.0, 1.0] # chart
    #   19: [1.0, 1.0] # formula_number
    #   20: [1.0, 1.0] # header_image
    #   21: [1.0, 1.0] # footer_image
    #   22: [1.0, 1.0] # aside_text
    # layout_merge_bboxes_mode: 
    #   0: "large"  # paragraph_title
    #   1: "large"  # image
    #   2: "union"  # text
    #   3: "union"  # number
    #   4: "union"  # abstract
    #   5: "union"  # content
    #   6: "union"  # figure_title
    #   7: "large"  # formula
    #   8: "union"  # table
    #   9: "union"  # table_title
    #   10: "union" # reference
    #   11: "union" # doc_title
    #   12: "union" # footnote
    #   13: "union" # header
    #   14: "union" # algorithm
    #   15: "union" # footer
    #   16: "small" # seal
    #   17: "union" # chart_title
    #   18: "large" # chart
    #   19: "union" # formula_number
    #   20: "union" # header_image
    #   21: "union" # footer_image
    #   22: "union" # aside_text
SubPipelines:
  DocPreprocessor:
    SubModules:
      DocOrientationClassify:
        model_dir: /Users/doudou/.paddlex/official_models/PP-LCNet_x1_0_doc_ori
        model_name: PP-LCNet_x1_0_doc_ori
        module_name: doc_text_orientation
      DocUnwarping:
        model_dir: /Users/doudou/.paddlex/official_models/UVDoc
        model_name: UVDoc
        module_name: image_unwarping
    pipeline_name: doc_preprocessor
    use_doc_orientation_classify: true
    use_doc_unwarping: true
  SealOCR:
    SubModules:
      TextDetection:
        box_thresh: 0.6
        limit_side_len: 736
        limit_type: min
        max_side_len: 4000
        model_dir: /Users/doudou/.paddlex/official_models/PP-OCRv4_server_seal_det
        model_name: PP-OCRv4_server_seal_det
        module_name: seal_text_detection
        thresh: 0.2
        unclip_ratio: 0.5
      TextRecognition:
        batch_size: 1
        model_dir: /Users/doudou/.paddlex/official_models/PP-OCRv4_server_rec
        model_name: PP-OCRv4_server_rec
        module_name: text_recognition
        score_thresh: 0
    pipeline_name: OCR
    text_type: seal
    use_doc_preprocessor: false
    use_textline_orientation: false
pipeline_name: seal_recognition
use_doc_preprocessor: true
use_layout_detection: true
